insert station_exit set exit_id=1, station_id=1, exit_street="проспект Чернышевского", building_number="20";
insert station_exit set exit_id=2, station_id=2, exit_street="площадь Восстания", building_number="2А";
insert station_exit set exit_id=3, station_id=2, exit_street="площадь Восстания", building_number="1А";
insert station_exit set exit_id=4, station_id=2, exit_street="Невский проспект", building_number="85";
insert station_exit set exit_id=5, station_id=2, exit_street="Лиговский проспект", building_number="16";
insert station_exit set exit_id=6, station_id=2, exit_street="Гончарная", building_number="1";
insert station_exit set exit_id=7, station_id=3, exit_street="Большая Московская", building_number="2";
insert station_exit set exit_id=8, station_id=3, exit_street="Кузнечный переулок", building_number="1";
insert station_exit set exit_id=9, station_id=4, exit_street="Загородный проспект", building_number="50";
insert station_exit set exit_id=10, station_id=6, exit_street="площадь Балтийского вокзала", building_number="1";
insert station_exit set exit_id=11, station_id=7, exit_street="Звёздная", building_number="3к1";
insert station_exit set exit_id=12, station_id=8, exit_street="Московский проспект", building_number="28";
insert station_exit set exit_id=13, station_id=9, exit_street="Сенная площадь", building_number="2А";
insert station_exit set exit_id=14, station_id=10, exit_street="Невский проспект", building_number="30";
insert station_exit set exit_id=15, station_id=10, exit_street="набережная канала Грибоедова", building_number="16";
insert station_exit set exit_id=16, station_id=11, exit_street="Савушкина", building_number="2А";
insert station_exit set exit_id=17, station_id=12, exit_street="Невский проспект", building_number="35";
insert station_exit set exit_id=18, station_id=12, exit_street="Садовая", building_number="17";
insert station_exit set exit_id=19, station_id=14, exit_street="площадь Александра Невского", building_number="2";
insert station_exit set exit_id=20, station_id=15, exit_street="Сенная площадь", building_number="2Б";
insert station_exit set exit_id=21, station_id=16, exit_street="Владимирский проспект", building_number="23";
insert station_exit set exit_id=22, station_id=17, exit_street="Лиговский проспект", building_number="88";
insert station_exit set exit_id=23, station_id=18, exit_street="Чернорецкий переулок", building_number="3";
insert station_exit set exit_id=24, station_id=19, exit_street="Торфяная дорога", building_number="4";
insert station_exit set exit_id=25, station_id=20, exit_street="Кирпичный переулок", building_number="1";
insert station_exit set exit_id=26, station_id=21, exit_street="Ефимова", building_number="1А";
insert station_exit set exit_id=27, station_id=21, exit_street="Ефимова", building_number="1Б";
insert station_exit set exit_id=28, station_id=21, exit_street="Сенная площадь", building_number="7А";
insert station_exit set exit_id=29, station_id=21, exit_street="Сенная площадь", building_number="11А";
insert station_exit set exit_id=30, station_id=22, exit_street="Звенигородская", building_number="1к2";
insert station_exit set exit_id=31, station_id=23, exit_street="Лиговский проспект", building_number="153А";